#!/usr/bin/python3
#author hai
#time 2019-09-10

import os
import sys
import time
import re
import xlsxwriter
import hashlib
import requests
import smtplib
from email.header import Header
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

host = []
IpFirst = '192.168.1.'
for j in range(1,5):
    a = IpFirst + str( j + 1 )
    host.append(a)
ping_result = []
for Ipadd in host:
    cmds = 'ping -c1 -W1 %s &> /dev/null' % Ipadd 
    p = os.system(cmds)
    if  p == 0:
        a = '是'
    else:
        a = '否'
    ping_result.append(a)
#print(host,b)

title_room = [
u"IP地址",
u"是否PING通",
]
wbk = xlsxwriter.Workbook(u'IP-Ping.xlsx')
title_format = wbk.add_format({
'bold': False, #字体加粗
'border':1, #单元格边框宽度
'align':'center', #水平对齐方式
'valign':'vcenter', #垂直对齐方式
'font_size':14,  #字体大小
'text_wrap': True, #是否自动换行
'fg_color':'#FFFFFF' #单元格背景颜色
})
common_format = wbk.add_format({
'align':'center',
'valign':'vcenter',
'font_size':12,
'border':1
})
sheet = wbk.add_worksheet(u'IP')
sheet.set_row(0, 20)
sheet.set_column('A:A',18)#设置单元格宽度
sheet.set_column('B:B',16)#设置单元格宽度
sheet.write_row('A1', title_room, title_format)
sheet.write_column('A2',host,title_format)
sheet.write_column('B2',ping_result,title_format)
wbk.close()


def sendmail():
 #   excel.handle_excel()
# 第三方 SMTP 服务
    mail_host = "mail.cri.cn"      # SMTP服务器
#    mail_pass = "yxHaeSn6Ma"               # 授权密码，非登录密码
    mail_pass = "xxxxxx"               # 授权密码，非登录密码

    sender = 'aaa@cri.cn'    # 发件人邮箱(最好写全, 不然会失败)
    receivers = ['aaa@cri.cn']# 接收邮件，可设置为你的QQ邮箱或者其他邮箱
    #receivers = ['aaa@qq.cn']# 接收邮件，可设置为你的QQ邮箱或者其他邮箱
    acc = ['aaa@163.cn']  #抄送邮件
    #acc = ['bbb@163.cn']  #抄送邮件

    xlsFile = 'IP-Ping.xlsx'
    xlsApart = MIMEApplication(open(xlsFile, 'rb').read())
    xlsApart.add_header('Content-Disposition', 'attachment', filename=xlsFile)

    content = '各位好:\n     附件为该网段IP,PING的结果，请查收！'
    title = 'IP PING结果'  # 邮件主题
    textApart = MIMEText(content, 'plain', 'utf-8')  # 内容, 格式, 编码

    m = MIMEMultipart()
    m.attach(textApart)
    m.attach(xlsApart)
    m['From'] = sender
    m['TO'] = ','.join(receivers)
    m['Cc'] = ','.join(acc)
    m['Subject'] = Header(title).encode()
    try:
        smtpObj = smtplib.SMTP(mail_host)
        smtpObj.login(sender, mail_pass)  # 登录验证
        smtpObj.sendmail(sender, receivers+acc, m.as_string())  # 发送
        #print("mail has been send successfully.")
        smtpObj.quit()
    except smtplib.SMTPException as e:
        print(e)

### end send ###
### main ###
if __name__ == "__main__":
    #handle_excel()
    #live.ws_resault()
    sendmail()
### END ###
